CREATE TABLE IF NOT EXISTS STORE (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME TEXT NOT NULL,
    LOGO VARCHAR(255),
    HOME_IMAGE VARCHAR(255),
    DEALS_IMAGE VARCHAR(255),
    INTERACTIVE_IMAGE VARCHAR(255),
    SELLER_ID INT,
    FOREIGN KEY (SELLER_ID) REFERENCES SELLER(ID)
    )