CREATE TABLE IF NOT EXISTS user
(
    ID       INT AUTO_INCREMENT NOT NULL PRIMARY KEY,

    CLIENT_NAME     VARCHAR(50),
    EMAIL    VARCHAR(100),
    PASSWORD VARCHAR(250),
    ADDRESS  VARCHAR(200)

);