CREATE TABLE CART
(
    ID      BIGINT PRIMARY KEY,
    USER_ID BIGINT UNIQUE
);

CREATE TABLE CART_LINE
(
    ID         BIGINT PRIMARY KEY,
    QUANTITY   INT          NOT NULL CHECK ( QUANTITY >= 0 ),
    CART_ID    BIGINT,
    VARIANT_ID BIGINT,
    FOREIGN KEY (CART_ID) REFERENCES CART (ID)
);