INSERT IGNORE INTO product (title, description, main_picture, status, create_at, updated_at, category_id)
VALUES
    ('Product 3', 'Description 3', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Mouse_1x._SY116_CB667159063_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 4', 'Description 4', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 5', 'Description 5', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 6', 'Description 6', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 7', 'Description 7', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 2),
    ('Product 8', 'Description 8', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 9', 'Description 9', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 2),
    ('Product 10', 'Description 10', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 11', 'Description 11', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 12', 'Description 12', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 2),
    ('Product 13', 'Description 13', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 2),
    ('Product 14', 'Description 14', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 15', 'Description 15', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 2),
    ('Product 16', 'Description 16', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 17', 'Description 17', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 2),
    ('Product 18', 'Description 18', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 2),
    ('Product 19', 'Description 19', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 20', 'Description 20', 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2022/February/DashboardCards/GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 21', 'Description 21', 'https://m.media-amazon.com/images/I/61HuQ1hENrL._AC_SY200_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 22', 'Description 22', 'https://m.media-amazon.com/images/I/61HuQ1hENrL._AC_SY200_.jpg', 'Active', NOW(), NOW(), 2),
    ('Product 23', 'Description 23', 'https://m.media-amazon.com/images/I/61HuQ1hENrL._AC_SY200_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 24', 'Description 24', 'https://m.media-amazon.com/images/I/61HuQ1hENrL._AC_SY200_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 25', 'Description 25', 'https://m.media-amazon.com/images/I/61HuQ1hENrL._AC_SY200_.jpg', 'Active', NOW(), NOW(), 2),
    ('Product 26', 'Description 26', 'https://m.media-amazon.com/images/I/61HuQ1hENrL._AC_SY200_.jpg', 'Active', NOW(), NOW(), 1),
    ('Product 27', 'Description 27', 'https://m.media-amazon.com/images/I/61HuQ1hENrL._AC_SY200_.jpg', 'Active', NOW(), NOW(), 2),
    ('Product 28', 'Description 28', 'https://m.media-amazon.com/images/I/61HuQ1hENrL._AC_SY200_.jpg', 'Active', NOW(), NOW(), 2);

