INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Xanh Lam', 1);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Đỏ', 1);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('S', 2);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('M', 2);

