INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Xanh', 1);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Do', 1);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('S', 2);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('M', 2);

