INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Blue', 1);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Red', 1);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('S', 2);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('M', 2);

