INSERT IGNORE INTO OPTION_TABLE (name,product_id) VALUES ('Mau',1);
INSERT IGNORE INTO OPTION_TABLE (name,product_id) VALUES ('Size',1);
INSERT IGNORE INTO OPTION_TABLE (name,product_id) VALUES ('Mau',2);
INSERT IGNORE INTO OPTION_TABLE (name,product_id) VALUES ('Size',2);
INSERT IGNORE INTO OPTION_TABLE (name,product_id) VALUES ('Mau',3);
INSERT IGNORE INTO OPTION_TABLE (name,product_id) VALUES ('Size',3);
