INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Xanh Lam', 1);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Đỏ', 1);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('S', 2);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('M', 2);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('RED', 3);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('MIN', 3);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('S', 4);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('M', 4);
    INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('RED', 5);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('MIN', 5);
    INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('XL', 6);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('XL', 6);

