# ALTER TABLE SHOP_ORDER DROP FOREIGN KEY CART_LINE;
# ALTER TABLE SHOP_ORDER DROP COLUMN MESSAGE;
# ALTER TABLE SHOP_ORDER DROP COLUMN PAYMENT_METHOD;
# ALTER TABLE SHOP_ORDER ADD INT QUANTIY;
# ALTER TABLE SHOP_ORDER ADD FOREIGN KEY (VARIANT_ID) REFERENCES VARIANT(ID);
